FROM node:latest AS base

WORKDIR /usr/src
COPY shared shared
COPY app/client-utils/home.js app/client-utils/home.js

WORKDIR /usr/src/shared
RUN npm install
RUN npm run build

FROM node:20-alpine AS production
WORKDIR /usr/src/shared

COPY shared/package*.json ./
RUN npm install --production

COPY --from=base /usr/src/shared/dist ./dist
COPY --from=base /usr/src/shared/settings/index.html ./dist/settings/index.html
COPY --from=base /usr/src/shared/settings/settings.js ./dist/settings/settings.js
COPY --from=base /usr/src/app/client-utils/home.js ./dist/client-utils/home.js
COPY --from=base /usr/src/shared/client-utils/play.js ./dist/client-utils/play.js

CMD ["node", "dist/shared-server.js"]
