FROM node:latest AS base

WORKDIR /src
# COPY package*.json .
# RUN npm install

# FROM base AS dev
# COPY ./ ./
COPY play play
COPY shared shared

WORKDIR /src/play
RUN npm install

# RUN npm run build 
RUN cd ../shared && npm install && npm run build
RUN cd ../play && npm run build

FROM node:20-alpine AS production

WORKDIR /usr/src/app
COPY play/package*.json ./
RUN npm install --production

COPY --from=base /src/play/dist ./
COPY --from=base /src/shared/dist ../shared/dist
COPY --from=base /src/shared/node_modules ../shared/node_modules
COPY play/index.html ./

CMD ["node", "server.js"]