# version: '3'
services: 
  shared:
    build:
      context: .
      dockerfile: Dockerfile.shared
  app:
    build: # ./app 
      context: .
      dockerfile: Dockerfile.app # ./app/Dockerfile
    # depends_on:
    #   - shared
  auth:
    # image: node:latest
    # volumes:
    #   - ./auth:/opt/app
    # command: node /opt/app/auth.js
    build:
      context: .
      dockerfile: Dockerfile.auth
  play:
    build: # ./play
      context: .
      dockerfile: Dockerfile.play
  collab:
    build: ./collab
  nginx:
    image: nginx:latest
    ports:
      - "1313:8080"
    volumes:
      - ./nginx/lb.conf:/etc/nginx/conf.d/lb.conf
      - ./nginx/401.html:/etc/nginx/401.html
    depends_on:
      - app
      - shared
      - auth
      - play
      - collab
