# version: '3'
services: 
  # shared:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.shared
  app:
    build: # ./app 
      context: .
      dockerfile: Dockerfile.app # ./app/Dockerfile
    # depends_on:
    #   - shared
  websock:
    image: node:latest
    volumes:
      - ./websock:/opt/app
    command: node /opt/app/websock.js
  play:
    build: # ./play
      context: .
      dockerfile: Dockerfile.play
  collab:
    build: ./collab
  nginx:
    image: nginx:latest
    ports:
      - "1313:8080"
    volumes:
      - ./nginx/lb.conf:/etc/nginx/conf.d/lb.conf
    depends_on:
      - app
      - websock
      - play
      - collab
